#pragma once

#include "xparameters.h"
#include "xuartlite.h"
#include "xintc.h"
#include "xil_exception.h"
#include "xil_printf.h"
#include "xtmrctr.h"
#include "xwdttb.h"
#include "xil_cache.h"
#include "xsysmon.h"
#include "xstatus.h"

#include "fpga_build.h"
#include "gpio.h"
#include "oled.h"
#include "adc.h"
#include "uart.h"
#include "stamp.h"
#include "xlprint.h"
#include "lib.h"
#include "post.h"
